import type { BoardProfile } from "./boards";
import type { MatrixPlan } from "./matrix";

function pinArrayLiteral(pins: string[]): string {
  // RP2040 pins are written as GP0, GP1, ... which the arduino-pico core
  // accepts directly as numeric-like macros; Pro Micro / ESP32-S3 use bare
  // numbers.
  return `{ ${pins.join(", ")} }`;
}

function header(board: BoardProfile, plan: MatrixPlan): string {
  return `/*
 * Auto-generated by Button Box Matrix Planner.
 * Board: ${board.name}
 * Matrix: ${plan.rows} rows x ${plan.cols} cols = ${plan.rows * plan.cols} cells (${plan.buttonCount} buttons wired, ${plan.unusedCells} unused)
 * HID buttons: ${plan.buttonCount}
 *
 * Diode orientation: ${plan.diode.orientation}
 *
 * Setup notes:
${board.notes.map((n) => ` *  - ${n}`).join("\n")}
 */

`;
}

function scanCore(plan: MatrixPlan): string {
  return `const uint8_t ROWS = ${plan.rows};
const uint8_t COLS = ${plan.cols};
const uint8_t NUM_BUTTONS = ${plan.buttonCount};

const uint8_t rowPins[ROWS] = ${pinArrayLiteral(plan.rowPins)};
const uint8_t colPins[COLS] = ${pinArrayLiteral(plan.colPins)};

// hidIndexOf[row][col] = HID button index for that matrix cell, or 255 if unused.
const uint8_t hidIndexOf[ROWS][COLS] = {
${plan.cells
  .reduce<string[][]>((rowsAcc, cell) => {
    if (!rowsAcc[cell.row]) rowsAcc[cell.row] = [];
    rowsAcc[cell.row][cell.col] = cell.isUnused ? "255" : String(cell.hidIndex);
    return rowsAcc;
  }, [])
  .map((row) => `  { ${row.join(", ")} }`)
  .join(",\n")}
};

bool buttonState[NUM_BUTTONS];
bool lastButtonState[NUM_BUTTONS];

const uint8_t DEBOUNCE_MS = 5;
unsigned long lastDebounceTime[NUM_BUTTONS];

void scanMatrix() {
  for (uint8_t r = 0; r < ROWS; r++) {
    digitalWrite(rowPins[r], LOW);
    delayMicroseconds(20); // let the row line settle before reading columns

    for (uint8_t c = 0; c < COLS; c++) {
      uint8_t hidIndex = hidIndexOf[r][c];
      if (hidIndex == 255) continue; // unpopulated cell

      bool pressed = (digitalRead(colPins[c]) == LOW);
      unsigned long now = millis();

      if (pressed != lastButtonState[hidIndex]) {
        lastDebounceTime[hidIndex] = now;
      }
      if (now - lastDebounceTime[hidIndex] > DEBOUNCE_MS) {
        buttonState[hidIndex] = pressed;
      }
      lastButtonState[hidIndex] = pressed;
    }

    digitalWrite(rowPins[r], HIGH);
  }
}

void setupMatrixPins() {
  for (uint8_t r = 0; r < ROWS; r++) {
    pinMode(rowPins[r], OUTPUT);
    digitalWrite(rowPins[r], HIGH);
  }
  for (uint8_t c = 0; c < COLS; c++) {
    pinMode(colPins[c], INPUT_PULLUP);
  }
}
`;
}

function arduinoJoystickSketch(board: BoardProfile, plan: MatrixPlan): string {
  return `${header(board, plan)}#include <Joystick.h>

Joystick_ Joystick(
  JOYSTICK_DEFAULT_REPORT_ID,
  JOYSTICK_TYPE_GAMEPAD,
  NUM_BUTTONS, 0,      // button count, hat switch count
  false, false, false, // no X/Y/Z axis
  false, false, false, // no Rx/Ry/Rz
  false, false,        // no rudder/throttle
  false, false, false  // no accelerator/brake/steering
);

${scanCore(plan)}
void setup() {
  setupMatrixPins();
  Joystick.begin(false); // manual sendState() so we only send on change
}

void loop() {
  scanMatrix();

  bool changed = false;
  for (uint8_t i = 0; i < NUM_BUTTONS; i++) {
    if (buttonState[i] != Joystick.getButton(i)) {
      Joystick.setButton(i, buttonState[i]);
      changed = true;
    }
  }
  if (changed) Joystick.sendState();
}
`;
}

function tinyUsbGamepadSketch(board: BoardProfile, plan: MatrixPlan): string {
  return `${header(board, plan)}#include <Adafruit_TinyUSB.h>

uint8_t const desc_hid_report[] = {
  TUD_HID_REPORT_DESC_GAMEPAD()
};

Adafruit_USBD_HID usb_hid;

${scanCore(plan)}
hid_gamepad_report_t lastReport;

void setup() {
  setupMatrixPins();

  usb_hid.setPollInterval(2);
  usb_hid.setReportDescriptor(desc_hid_report, sizeof(desc_hid_report));
  usb_hid.begin();

  memset(&lastReport, 0, sizeof(lastReport));

#if defined(ARDUINO_ARCH_ESP32)
  // ESP32-S3: requires Tools > USB Mode: "USB-OTG (TinyUSB)"
  while (!TinyUSBDevice.mounted()) delay(1);
#else
  while (!TinyUSBDevice.mounted()) delay(1);
#endif
}

void loop() {
  scanMatrix();

  uint32_t buttons = 0;
  for (uint8_t i = 0; i < NUM_BUTTONS; i++) {
    if (buttonState[i]) buttons |= (1UL << i);
  }

  if (buttons != lastReport.buttons) {
    hid_gamepad_report_t report;
    memset(&report, 0, sizeof(report));
    report.buttons = buttons;

    if (usb_hid.ready()) {
      usb_hid.sendReport(0, &report, sizeof(report));
      lastReport = report;
    }
  }
}
`;
}

export function generateSketch(board: BoardProfile, plan: MatrixPlan): string {
  return board.hidStrategy === "arduino-joystick"
    ? arduinoJoystickSketch(board, plan)
    : tinyUsbGamepadSketch(board, plan);
}
