import type { Plan } from "./plan";

function header(plan: Plan): string {
  const { board, matrix, encoders, totalHidButtons } = plan;

  const matrixDesc = matrix
    ? ` * Matrix: ${matrix.rows} rows x ${matrix.cols} cols = ${matrix.rows * matrix.cols} cells (${matrix.buttonCount} buttons wired, ${matrix.unusedCells} unused)\n`
    : ` * No button matrix (no momentary buttons / encoder push-buttons configured)\n`;

  const encoderDesc = encoders.length
    ? ` * Rotary encoders: ${encoders.length} (2 HID buttons each: CW pulse + CCW pulse)\n`
    : "";

  const diodeDesc = matrix
    ? ` * Diode orientation: ${matrix.diode.orientation}\n *\n`
    : "";

  return `/*
 * Auto-generated by Button Box Matrix Planner.
 * Board: ${board.name}
${matrixDesc}${encoderDesc} * Total HID buttons: ${totalHidButtons}
 *
${diodeDesc} * Setup notes:
${board.notes.map((n) => ` *  - ${n}`).join("\n")}
 */

`;
}

function matrixSection(plan: Plan): string {
  const m = plan.matrix;
  if (!m) return "";

  const hidGrid = m.cells
    .reduce<string[][]>((rowsAcc, cell) => {
      if (!rowsAcc[cell.row]) rowsAcc[cell.row] = [];
      rowsAcc[cell.row][cell.col] = cell.isUnused ? "255" : String(cell.hidIndex);
      return rowsAcc;
    }, [])
    .map((row) => `  { ${row.join(", ")} }`)
    .join(",\n");

  return `const uint8_t ROWS = ${m.rows};
const uint8_t COLS = ${m.cols};

const uint8_t rowPins[ROWS] = { ${m.rowPins.join(", ")} };
const uint8_t colPins[COLS] = { ${m.colPins.join(", ")} };

// hidIndexOf[row][col] = HID button index for that matrix cell, or 255 if unused.
const uint8_t hidIndexOf[ROWS][COLS] = {
${hidGrid}
};

const uint8_t DEBOUNCE_MS = 5;
unsigned long lastDebounceTime[NUM_BUTTONS];
bool lastRawState[NUM_BUTTONS];

void scanMatrix() {
  for (uint8_t r = 0; r < ROWS; r++) {
    digitalWrite(rowPins[r], LOW);
    delayMicroseconds(20); // let the row line settle before reading columns

    for (uint8_t c = 0; c < COLS; c++) {
      uint8_t hidIndex = hidIndexOf[r][c];
      if (hidIndex == 255) continue; // unpopulated cell

      bool pressed = (digitalRead(colPins[c]) == LOW);
      unsigned long now = millis();

      if (pressed != lastRawState[hidIndex]) {
        lastDebounceTime[hidIndex] = now;
      }
      if (now - lastDebounceTime[hidIndex] > DEBOUNCE_MS) {
        buttonState[hidIndex] = pressed;
      }
      lastRawState[hidIndex] = pressed;
    }

    digitalWrite(rowPins[r], HIGH);
  }
}

void setupMatrixPins() {
  for (uint8_t r = 0; r < ROWS; r++) {
    pinMode(rowPins[r], OUTPUT);
    digitalWrite(rowPins[r], HIGH);
  }
  for (uint8_t c = 0; c < COLS; c++) {
    pinMode(colPins[c], INPUT_PULLUP);
  }
}
`;
}

function encoderSection(plan: Plan): string {
  const { encoders } = plan;
  if (encoders.length === 0) return "";

  const firstEncoderHidIndex = plan.matrix ? plan.matrix.buttonCount : 0;

  const declarations = encoders.map((e) => `Encoder enc${e.index}(${e.pinA}, ${e.pinB});`).join("\n");
  const positions = encoders.map((e) => `long encPos${e.index} = 0;`).join("\n");
  const updates = encoders
    .map(
      (e) => `
  delta = enc${e.index}.read() - encPos${e.index};
  if (delta >= STEPS_PER_DETENT) {
    pulseUntil[${e.cwHidIndex}] = millis() + PULSE_HOLD_MS;
    encPos${e.index} += STEPS_PER_DETENT;
  } else if (delta <= -STEPS_PER_DETENT) {
    pulseUntil[${e.ccwHidIndex}] = millis() + PULSE_HOLD_MS;
    encPos${e.index} -= STEPS_PER_DETENT;
  }`
    )
    .join("\n");

  return `#include <Encoder.h>

${declarations}
${positions}

// Typical mechanical rotary encoder: 4 quadrature counts per detent —
// adjust to 1 or 2 if yours reads too fast/slow per click.
const int8_t STEPS_PER_DETENT = 4;
// How long a CW/CCW "button" stays pressed so the host reliably registers it.
const uint16_t PULSE_HOLD_MS = 30;
unsigned long pulseUntil[NUM_BUTTONS];

void updateEncoders() {
  long delta;
${updates}

  unsigned long now = millis();
  for (uint8_t i = ${firstEncoderHidIndex}; i < NUM_BUTTONS; i++) {
    buttonState[i] = now < pulseUntil[i];
  }
}
`;
}

function arduinoJoystickSketch(plan: Plan): string {
  return `${header(plan)}#include <Joystick.h>

const uint8_t NUM_BUTTONS = ${plan.totalHidButtons};
bool buttonState[NUM_BUTTONS];

Joystick_ Joystick(
  JOYSTICK_DEFAULT_REPORT_ID,
  JOYSTICK_TYPE_GAMEPAD,
  NUM_BUTTONS, 0,      // button count, hat switch count
  false, false, false, // no X/Y/Z axis
  false, false, false, // no Rx/Ry/Rz
  false, false,        // no rudder/throttle
  false, false, false  // no accelerator/brake/steering
);

${matrixSection(plan)}
${encoderSection(plan)}
void setup() {
  ${plan.matrix ? "setupMatrixPins();" : ""}
  Joystick.begin(false); // manual sendState() so we only send on change
}

void loop() {
  ${plan.matrix ? "scanMatrix();" : ""}
  ${plan.encoders.length ? "updateEncoders();" : ""}

  bool changed = false;
  for (uint8_t i = 0; i < NUM_BUTTONS; i++) {
    if (buttonState[i] != Joystick.getButton(i)) {
      Joystick.setButton(i, buttonState[i]);
      changed = true;
    }
  }
  if (changed) Joystick.sendState();
}
`;
}

function tinyUsbGamepadSketch(plan: Plan): string {
  return `${header(plan)}#include <Adafruit_TinyUSB.h>

const uint8_t NUM_BUTTONS = ${plan.totalHidButtons};
bool buttonState[NUM_BUTTONS];

uint8_t const desc_hid_report[] = {
  TUD_HID_REPORT_DESC_GAMEPAD()
};

Adafruit_USBD_HID usb_hid;

${matrixSection(plan)}
${encoderSection(plan)}
hid_gamepad_report_t lastReport;

void setup() {
  ${plan.matrix ? "setupMatrixPins();" : ""}

  usb_hid.setPollInterval(2);
  usb_hid.setReportDescriptor(desc_hid_report, sizeof(desc_hid_report));
  usb_hid.begin();

  memset(&lastReport, 0, sizeof(lastReport));

  while (!TinyUSBDevice.mounted()) delay(1);
}

void loop() {
  ${plan.matrix ? "scanMatrix();" : ""}
  ${plan.encoders.length ? "updateEncoders();" : ""}

  uint32_t buttons = 0;
  for (uint8_t i = 0; i < NUM_BUTTONS; i++) {
    if (buttonState[i]) buttons |= (1UL << i);
  }

  if (buttons != lastReport.buttons) {
    hid_gamepad_report_t report;
    memset(&report, 0, sizeof(report));
    report.buttons = buttons;

    if (usb_hid.ready()) {
      usb_hid.sendReport(0, &report, sizeof(report));
      lastReport = report;
    }
  }
}
`;
}

export function generateSketch(plan: Plan): string {
  return plan.board.hidStrategy === "arduino-joystick"
    ? arduinoJoystickSketch(plan)
    : tinyUsbGamepadSketch(plan);
}
